Lab10/urls.py
from django.conf.urls import url
from .views import subscribe, user_validate, unsub 
from django.views.generic.base import RedirectView

app_name = "Lab10"
urlpatterns = [
	url('subscribe/', subscribe, name = 'subscribe'),
    url('cekvalidasi/', user_validate , name="cekvalidasi"),
	url('hapusSub/', unsub, name = 'unsub'),
]

Lab6/urls.py
from django.conf.urls import url
from .views import index, add_todo, show_identitas, list_buku, daftar_buku, login, logout
from . import views
from django.urls import include
    #url for app
app_name = "Lab6"
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_todo', add_todo, name='add_todo'),
    url(r'^identitas', show_identitas, name='identitas'),
	url(r'^listbuku', list_buku, name='listbuku'),
	url(r'^list_buku', daftar_buku, name='list_buku'),
	url('login/', login, name='login'),
    url('logout/', logout, name='logout'),
	
    

        
]

PPWLab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import Lab6.urls as Lab6
import Lab10.urls as Lab10

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^lab-6/', include(Lab6,namespace='Lab6')),
    url(r'^lab-10/', include(Lab10,namespace='Lab10')),
	path('auth/', include('social_django.urls', namespace='social')),
]

Lab10/models.py
# Create your models here.
from django.db import models

# models of regist subscriber
class RegisterSubscriber(models.Model):
    nama = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=30)

Lab6/models.py
from django import forms
from django.db import models
from django.utils import timezone
from datetime import datetime, date


# Create your models here.
class Todo(models.Model):
    description = models.TextField()
    time = models.DateTimeField(auto_now_add = True)

Lab10/forms.py
from django import forms
from .models import RegisterSubscriber

# implement forms using ModelForm
class SubscriberForm(forms.ModelForm):
    class Meta:
        model = RegisterSubscriber
        fields = ['nama', 'email', 'password']
        widgets = {
            'nama': forms.TextInput(
                attrs={'class': 'form-control', 'id':'nama_form', 'placeholder': 'Isi nama' , 'maxlength': 30}),

            'email': forms.TextInput(
                attrs={'type':'email','class': 'form-control', 'id':'email_form','placeholder': 'Isi email', 'maxlength': 50}),
            
            'password': forms.TextInput(
                attrs={ 'type':'password' ,'class': 'form-control', 'id':'password_form','placeholder': 'Isi password', 'maxlength': 30}),
        }

Lab6/forms.py
from django import forms

from django.forms import Form
from .models import Todo


class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan status...'
    }
    description = forms.CharField(label='', required=True, max_length=300, widget=forms.Textarea(attrs=description_attrs))
    time = forms.DateTimeInput(attrs={'class': 'form-control'})

class Meta :
    model = Todo
    fields = ['description']

Lab10/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from .forms import SubscriberForm
from .models import RegisterSubscriber
import requests, json, re


# function POST request subscriber
@csrf_exempt
def subscribe(request):
    get_user_acccount = RegisterSubscriber.objects.all()
    if request.method == "POST":
        form_value = SubscriberForm(request.POST or None)
        nama = request.POST['nama']
        email = request.POST['email']
        password = request.POST['password']
        user_filter_email = RegisterSubscriber.objects.filter(email=email)
        if (len(user_filter_email) > 0):
            response_message = 'Use another email!'
        else:
            create_user = RegisterSubscriber(email=email, nama=nama, password=password)
            create_user.save()

    else:
        form_value = SubscriberForm()

    return render(request, 'subscribe.html', {'form': form_value})


@csrf_exempt
def user_validate(request):
    
    nama_validate_check = False
    email_validate_check = False
    password_validate_check = False
    
    if request.method == "POST":
        nama = request.POST['nama']
        email = request.POST['email']
        password = request.POST['password']

        # nama harus >= 4 dan <=50        
        if 4 <= len(nama) <= 50:
            nama_validate_check = True

        # email harus dicek
        if len(email) >= 8:
            email_validate_check = bool(re.match("^.+@(\[?)[a-zA-Z0-9-.]+.([a-zA-Z]{2,3}|[0-9]{1,3})(]?)$", email))

        # password harus lebih dr 8 dan kurang dari 50
        if 8 <= len(password) <= 50:
            password_validate_check = True

        # pesan kalo nama gasesuai
        if not nama_validate_check:
            return HttpResponse(json.dumps({'message': 'Name min 4 and max 30!'}), content_type="application/json")

        # pesan kalo email gasesuai
        if not email_validate_check:
            return HttpResponse(json.dumps({'message': 'Please enter the email correctly!'}), content_type="application/json")

        # pesan kalo email udh dipake
        user_filter_email = RegisterSubscriber.objects.filter(email=email)
        if len(user_filter_email) > 0:
            return HttpResponse(json.dumps({'message': 'Email already registered!'}), content_type="application/json")

        # kalo pas gasesuai
        if not password_validate_check:
            return HttpResponse(json.dumps({'message': 'Pass must contain at least 8 characters'}), content_type="application/json")

        return HttpResponse(json.dumps({'message': 'All fields are valid'}), content_type="application/json")

    else:
        return HttpResponse(json.dumps({'message': "Try again!"}), content_type="application/json")

def model_to_dict(obj):
	data = serializers.serialize('json',[obj,])
	struct = json.loads(data)
	data = json.dumps(struct[0]["fields"])
	return data

@csrf_exempt
def unsub(request):
	if request.method == "POST":
		subId = request.POST['id']
		RegisterSubscriber.objects.filter(id=subId).delete()
		return HttpResponse(json.dumps({'message': "Succeed"}),content_type="application/json")
	else:
		return HttpResponse(json.dumps({'message': "There's something wrong. Try again."}),content_type="application/json")

Lab6/views.py
from django.urls import reverse
from .forms import Todo_Form
from .models import Todo

from django.http import HttpResponseRedirect
from django.shortcuts import render

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import render, render_to_response
from django.template import RequestContext, loader
import datetime
import json
import requests
from django.contrib.auth import logout as logout_user

    # Create your views here.

response = {}
def index(request):
    response['author'] = "Oktafia" #TODO Implement yourname
    todo = Todo.objects.all()
    response['todo'] = todo
    response['todo_form'] = Todo_Form
    return render(request, 'to_do_list.html', response)

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST'):
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save(todo)
        return HttpResponseRedirect('/lab-6/')
    else:
        return HttpResponseRedirect('/lab-6/')

def show_identitas(request) :
    return render(request, 'biodata.html')


def list_buku(request) :
	return render(request, 'list_buku.html')

def daftar_buku(request) :
	data = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
	return HttpResponse(data, content_type='application/json')
	
def login(request):
    return render(request, 'login.html')

def logout(request):
    logout_user(request)
    return redirect('to_do_list.html')

Lab10/templates/subscribe.html
{% load static %}
<html>
        <title>Subscribe</title>
<head>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


</head>

<body>
 
  <style>
  body {background-color: powderblue;}
  </style>

  <div class="container">
    <div class="mt-5">
        <h2 style="text-align:center; "><b>Yuk di Subscribe!</b></h1>
    </div>


    <div class="mt-3" id="msg_response"></div>
    <!-- create user response -->
        
    <form class="form-group" method="POST" id="subscribe_form" onsubmit="return false;">
        {% csrf_token %} 
        {% for field in form %}
        <div class="form-group colorSub">
            <b>{{ field.label }} : {{ field }}</b>
        </div>
        {% endfor %}

        <div class="mt-4" id="msg_validate"></div>
      
      <div><center>
        <input id="subscribe_button" type="submit" value="Subscribe" class="btn btn-warning" disabled onclick="subscribe()"/>
      </center></div>
    </form>
	
		<br>
		<center><h1 class "text-main">My Subscriber</h1></center>
		
		<!-- <div id="listsub" class="card" style="margin:auto; margin-top: 5%; padding: 5%; background-color: rgba(0, 0, 0, 0.75); color: white !important;"> -->

		<table id="listsub" class="table table-hover table-striped" align="center" style="text-align: center">
			<tr>
				<th scope="col">Nama</th>
				<th scope="col">Email</th>
			</tr>
		{% if todo %}
			{%for data in todo %}
				<tr>
					<td scope="row">{{data.description}}</td>
					<td scope="row">{{data.time}}</td>
				</tr>	
			{%endfor%}
		

		</table>
	{%endif%}
  </div>
</body>
	<script>
	
		$(document).ready(function () {
		var x_timer;
		$("#nama_form").keyup(function (e) {
			clearTimeout(x_timer);
			var password = $(this).val();
			x_timer = setTimeout(function () {validate_user();}, 10);

		});
	});

	$(document).ready(function () {
		var x_timer;
		$("#email_form").keyup(function (e) {
			clearTimeout(x_timer);
			var email = $(this).val();
			x_timer = setTimeout(function () {validate_user();}, 10);
		});
	});

	$(document).ready(function () {
		var x_timer;
		$("#password_form").keyup(function (e) {
			clearTimeout(x_timer);
			var nama = $(this).val();
			x_timer = setTimeout(function () {validate_user();}, 10);
		});
	});

	function validate_user() {
		$.ajax({
			url: "/lab-10/cekvalidasi/",
			type: "POST",
			data: {
				nama: $('#nama_form').val(),
				email: $('#email_form').val(),
				password: $('#password_form').val()
			},

			success: function (response) {
				if (response.message == "All fields are valid"){
					document.getElementById('subscribe_button').disabled = false;
					$('#msg_validate').html("<p style='color:yellowgreen'>"+ response.message + "</p>")
				}
				else {
					document.getElementById('subscribe_button').disabled = true;
					$('#msg_validate').html("<p style='color:tomato'>"+ response.message + "</p>")
				}

			},
			error: function (errmsg) {

				alert("SORRY, ERROR DETECTED!");
			}

		});
	};
	var container = document.getElementById("listsub");
	function subscribe() {
		$.ajax({
			url: "lab-10/subcribe/",
			type: "POST",
			data: {
				nama: $('#nama_form').val(),            
				email: $('#email_form').val(),
				password: $('#password_form').val()
			},
			success: function (json) {
				console.log(json);
				$('#subscribe_form').val(''); // empty form
				$('#msg_response').html("<div class='alert alert-success'><strong>Success!</strong> THANKYOU FOR SUBSCRIBE!</div>")
				ambildata(json);
			},
			error: function (xhr, errmsg, err) {
				$('#msg_response').html("<div class='alert alert-danger'><strong>Error! </strong>SORRY, SERVER ERROR! </div>");
				alert("SORRY, ERROR DETECTED!");
			},
		});
	};
	
	function ambildata(data){
		htmlString = "<ul>";
		console.log(data.length)
		for (i=0;i<data.length;i++){
			htmlString+="<li>"+ " "+ "<button class='btn btn-secondary' onclick='hapusdata("+data[i].id + ")'>" + "Unsubscribe" + "</button>" + " "+ data[i].nama+" || " + data[i].email +  "</li>" +"<br>" 

		}
		container.insertAdjacentHTML('beforeend', htmlString+"</ul>")
	}

	
	
	
	




	
	</script>
</html>

Lab6/templates/biodata.html
{% load static %}
<html>
    <head>
        
        <title>My Profile</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'editing.css' %}">
        <script type="text/JavaScript" src="{% static 'function.js' %}"></script>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
        <script>
            $(document).ready(function() {
                    setTimeout(function(){
                        document.getElementById('load').style.visibility="hidden";
                        console.log("berhasil");
                    },2000);
                })
        </script>
    </head>

    <body bgcolor="#f9f098">
            <div id="load"></div>

        <div class="tema">
            <p> Select Your Theme here!</p>
        
          <input type="button" id="but1" value="Peach UI" onclick="warna('#E9967A')";/>
          <input type="button" id="but2" value="Blue Limes" onclick="warna('#48D1CC')";/>
        </div>
          <script>
               $(function() {
                    $( "#jQuery_accordion" ).accordion({
                    collapsible: true
                    });
                });
                
          </script>
          <p>Click on the buttons to open the collapsible content.</p> 
          <div id="jQuery_accordion">
            <h3>Aktivitas</h3>
                <ul>
                    <li>Kuliah</li>
                    <li>Kegiatan Organisasi</li>
                    <li>Kegiatan Kepanitiaan</li>
                    <li>Kegiatan Sosial</li>
                </ul>
            <h3>Pengalaman Organisasi dan Kepanitiaan</h3>
                <ul>
                    <li>Staff Divisi Peserta - BETIS</li>
                    <li>Staff Divisi Humas - Wisuda Ganjil</li>
                    <li>Volunteer Pengajar ComDev</li>
                    <li>Staff Departemen Pengabdian Masyarakat BEM Fasilkom UI</li>
                    <li>Staff KKM Fuki Fasilkom UI</li>
                    <li>Project Officer Rumah Belajar PocMan</li>
                    <li>Wakil Penanggung Jawab Divisi Dana Usaha - Siwak-NG</li>
                    <li>Wakil Penanggung Jawab Divisi Medis - PMB Fasilkom UI</li>
                </ul>
            <h3>Prestasi</h3>
              <div>
              <p>
                Best Staff Departemen Pengabdian Masyarakat BEM Fasilkom UI
              </p>
              </div>
          </div>

        <div id="fotoku">
            <img src = "https://scontent.fjkt1-1.fna.fbcdn.net/v/t1.0-9/42059178_103336817302689_3660655597667221504_n.jpg?_nc_cat=101&oh=3d2f19ac1f477699afe5614aded15a7a&oe=5C631340"  height="300" width="200" class="img-thumbnail" alt="Cinque Terre">
        </div>

        <div class="card bg-light mb-3" style="max-width: 18rem;" id="card1">
            <div class="card-block">
                <div class="card-header" >Biodata</div>
                    <div class="card-body">
                    <h5 class="card-title">Oktafia Sutanti</h5>
                    <p class="card-text">11 Oktober 1999</p>
                    <p class="card-text">Jln. Abdulrahman II No.108 Cibubur</p>
                    <p class="card-text">081299165668</p>
                    <p class="card-text">oktafia99@gmail.com</p>
                    </div>
                </div>
            </div> 
        </div>

        <div class="card bg-light mb-3" style="max-width: 25rem;" id="card2">
            <div class="card-block">
                <div class="card-header">Biodata</div>
                    <div class="card-body">
                      <h5 class="card-title">Pendidikan</h5>
                      <p class="card-text">2005-2011 SDN Cibubur 02 Pagi</p>
                      <p class="card-text">2011-2014 SMPN 91 Jakarta</p>
                      <p class="card-text">2014-2017 SMAN 39 Jakarta</p>
                      <p class="card-text">2017-sekarang Universitas Indonesia</p>
                    </div>
                </div>
            </div>
        </div>

        <div id="batas1">
        </div>

        <div class="card bg-light" id="deskripsi">
            <div class="card-block">
                <div class="card-body text-justify">
                    <p class="card-text">Saya merupakan mahasiswa Fakultas Ilmu Komputer Universitas Indonesia dengan Program Studi Sistem Informasi. Saya merupakan orang yang tertarik dengan isu Sosial yang ada di masyarakat. Saya memiliki hobi menonton film.</p>
                </div>
            </div>
        </div>


    </body>
</html>

Lab6/templates/list_buku.html
{% load static %}
<html>
    <head>
		<title>List Buku</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'editing.css' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="text/JavaScript" src="{% static 'function.js' %}"></script>
	</head>
	
	<body bgcolor="#48D1CC">
		<style>
		body {background-color: powderblue;}
		.buttonClicked{
			animation:blinkingText 0.8s infinite;
		}
		@keyframes blinkingText{
			0%{color: orange;}
			40%{color: transparent;}
			50%{color: transparent;}
			80%{color: orange;}
			100%{color: orange;}
		}
		</style>
		<center>
		<br>
		<h2 id="buka"> List Buku </h4>
		<br>
		
		<div> 
			<a class='btn btn-outline-dark' role='button' href='/lab-6/' > Log Out </a>
			<br>
			<br>
		</div>
		
		<center>
			{% if user.is_authenticated %} 
				Hello {{name}} !
			{% endif %} 
		</center>
		
		<p> Favourite Books : <input class="btn btn-primary" type="button"  id = "count" value="0"> </p>

		<button id="creative" type="button" class="btn btn-info" method="POST">Search books of Creative </button>
		<button id="art" type="button" class="btn btn-info" method="GET">Search books of Art </button>
		<button id="quilting" type="button" class="btn btn-info">Search books of Quilting </button>
		</center>
		
		<div class="main-div">
        <div class="container mx-auto d-block">
        <br>
			<table id="result" class="table table-hover table-striped" align="center" style="text-align: center">
				<thead>
					<tr>
						<th scope="col">Judul Buku</th>
						<th scope="col">Cover</th>
						<th scope="col"> Penulis </th>
						<th scope="col"> Penerbit </th>
						<th scope="col"> Add to Favourite </th>
					</tr>
				</thead>
        </div>
    </div>

	</body> 


	<script>
		$(document).on('click','#quilting', function(){
		$.ajax ({
			url : "/lab-6/list_buku/",
			//type : "get",
			//dataType : "json",
			success : function(data) {
				var tmp = "";
				for(var i = 0; i< data.items.length ; i++) {
					tmp += "<tbody><tr>" + "<td>" + data.items[i].volumeInfo.title + "</td>" +
					"<td><img src='"+ data.items[i].volumeInfo.imageLinks.thumbnail + "'></td>" +
					"<td>"+ data.items[i].volumeInfo.authors + "</td>" +
					"<td>"+ data.items[i].volumeInfo.publisher + "</td>" +
					"<td><a class='btn btn-outline-primary' href='#' role='button' id='fav'><i class='glyphicon glyphicon-star'></a></td>" + 
					 "</tr></tbody>"
				}
				$("#result").append(tmp);
			}
		});
		});	
		
		$(document).on('click','#fav', function(){
			$('#count').val(parseInt($('#count').val())+1);
			$(this).toggleClass("buttonClicked");
		});
		
		$(document).on('click','#creative', function(){
			$.ajax ({
			url : "https://www.googleapis.com/books/v1/volumes?q=creative",
			success : function(data) {
				var tmp = "";
				for(var i = 0; i< data.items.length ; i++) {
					tmp += "<tbody><tr>" + "<td>" + data.items[i].volumeInfo.title + "</td>" +
					"<td><img src='"+ data.items[i].volumeInfo.imageLinks.thumbnail + "'></td>" +
					"<td>"+ data.items[i].volumeInfo.authors + "</td>" +
					"<td>"+ data.items[i].volumeInfo.publisher + "</td>" +
					"<td><a class='btn btn-outline-primary' href='#' role='button' id='fav'><i class='glyphicon glyphicon-star'></a></td>" + 
					 "</tr></tbody>"
				}
				$("#result").append(tmp);
			}
		});
		});
		
		$(document).on('click','#art', function(){
			$.ajax ({
			url : "https://www.googleapis.com/books/v1/volumes?q=art",
			success : function(data) {
				var tmp = "";
				for(var i = 0; i< data.items.length ; i++) {
					tmp += "<tbody><tr>" + "<td>" + data.items[i].volumeInfo.title + "</td>" +
					"<td><img src='"+ data.items[i].volumeInfo.imageLinks.thumbnail + "'></td>" +
					"<td>"+ data.items[i].volumeInfo.authors + "</td>" +
					"<td>"+ data.items[i].volumeInfo.publisher + "</td>" +
					"<td><a class='btn btn-outline-primary' href='#' role='button' id='fav'><i class='glyphicon glyphicon-star'></a></td>" + 
					 "</tr></tbody>"
				}
				$("#result").append(tmp);
			}
		});
		});
		

	</script> 
	
	
</html>

Lab6/templates/login.html
{% block title %}

{% endblock %}

{% block content %}
{% load static %}
<html>
	<head>
		<title>Log In</title>
	</head>

<style>
#login {
    padding: 3em;
    margin-top: 10px;
}
body {background-color: powderblue;}
</style>

<div class="container">
    <div class="panel text-center" id="login">
        <h2>Silakan masuk dengan akun Google kamu</h2>
        <div class="btn btn-light my-2">
            <a href="{% url 'social:begin' 'google-oauth2' %}" style="text-decoration:none">
                <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
                Login with Google
            </a>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<!-- <script src="{% static 'script.js' %}"></script> -->
{% endblock %}

Lab6/templates/to_do_list.html
{% load static %}
<html>
	<head>
		<title>Home</title>
		<link rel="stylesheet" type="text/css" href="{% static 'editing.css' %}">
		<script type="text/JavaScript" src="{% static 'function.js' %}"></script>
		<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
		<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
		<script>
			document.onreadystatechange = function () {
				  setTimeout(function(){
					 document.getElementById('load').style.visibility="hidden";
				  },2000);
			  }
		</script>

	</head>

	<body  bgcolor="#f9f098">
			<div id="load"></div>
		<center><h1><font color="#5b4107NPM">Hello, Apa Kabar?</font></h1></center>
		<br>
		{% block content %}


		<div class="tema">
            <p> Select Your Theme here!</p>
        
          <input type="button" id="but1" value="Peach UI" onclick="warna('#E9967A')";/>
          <input type="button" id="but2" value="Blue Limes" onclick="warna('#48D1CC')";/>
        </div>

		<div> 
			<a class='btn btn-outline-dark' role='button' href='/lab-6/identitas/' > Lihat Profile Saya </a>
			<br>
			<br>
		</div>
		
		<div>
			<a class='btn btn-outline-dark' role='button' href ='/lab-6/listbuku/' > Lihat List Buku </a>
			<br>
			<br>
		</div>
		
		<div>
			<a class='btn btn-outline-dark' role='button' href ='/lab-6/login/' > Log In With Google and You Can Add Favorite List Buku </a>
			<br>
			<br>
		</div>

		<div>
			<a class='btn btn-outline-dark' role='button' href ='/lab-10/subscribe/' > Subscribe </a>
			<br>
			<br>
		</div>


		<form id="form" method="POST" action="{% url 'Lab6:add_todo' %}">
			{{ todo_form }}
			{% csrf_token %}
			{{ form.as_p }}
			<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
		</form>
		
		
		<br>

		{% if todo %}
		<center><h1 class "text-main"><font color="#5b4107NPM">My Status</font></h1></center>
		<table class="table table-hover table-striped" align="center" style="text-align: center">
			<tr>
				<th scope="col">Status</th>
				<th scope="col">Time</th>
			</tr>
			{%for data in todo %}
				<tr>
					<td scope="row">{{data.description}}</td>
					<td scope="row">{{data.time}}</td>
				</tr>	
			{%endfor%}
		
		{%else%}
			<br>
			<h1 class "text-main">Tidak Ada Status</h1>
		</table>
		{%endif%}

		{% endblock %}
	
	</body>
</html>